language: node_js
node_js:
  - node
cache:
  directories:
  - node_modules
script:
  - npm run build
#deploy:
#  provider: pages
#  skip_cleanup: true
#  github_token: $GITHUB_TOKEN 
#  keep_history: true
#  on:
#    branch: master
#  local_dir: dist